---
- hosts: control
  sudo: yes
  tasks:

  - name: get the latest gluster repo
    command: wget -P /etc/yum.repos.d http://download.gluster.org/pub/gluster/glusterfs/LATEST/RHEL/glusterfs-epel.repo creates=/etc/yum.repos.d/glusterfs-epel.repo

  - name: ensure the epel-release package is installed
    yum: name=epel-release state=present

  - name: install userspace-rcu development package
    yum: name=userspace-rcu-devel state=present

  - name: install gluster server package
    yum: name=glusterfs-server state=present

  - name: install firewalld package
    yum: name=firewalld state=present

  - name: ensure firewalld is running
    service: name=firewalld state=running

  - name: configure glusterd service firewall rules
    firewalld: port=24007-24009/tcp permanent=true immediate=true state=enabled

  - name: configure glusterd brick firewall rules
    firewalld: port=49152-49154/tcp permanent=true immediate=true state=enabled

  - name: start the gluster server services
    service: name=glusterd state=started

- hosts: control[0]
  sudo: yes
  tasks:

  - name: probe gluster peer
    command: gluster peer probe ucs-control02

  - name: create gluster volume glance
    command: gluster volume create glance replica 2 transport tcp ucs-control01:/mnt/gluster ucs-control02:/mnt/gluster force creates=/mnt/gluster
    register: vol_result

  - name: start gluster volume
    gluster_volume: state=started name=glance
    when: vol_result | success

- hosts: control
  sudo: yes
  tasks:

  - name: install glusterfs
    yum: name=glusterfs state=present

  - name: install gluster fuse
    yum: name=glusterfs-fuse state=present

  - name: make mnt directory
    file: path=/mnt/glance state=directory owner=root group=root mode=0755

  # - name: add fstab entry for mount point
  #   lineinfile:
  #     dest: /etc/fstab
  #     line: "{{ ansible_default_ipv4.address}}:glance /mnt/gluster-pool/ glusterfs defaults,_netdev 0 0"

  # - name: run the mount command
  #   command: mount -a

  - name: mount gluster storage on gluster-pool
    mount: name=/mnt/glance src="{{ansible_hostname}}:/glance" opts=defaults,_netdev fstype=glusterfs state=mounted
