---
- hosts: control[0]
  sudo: yes
  tasks:

  - name: install MySQL-python
    yum: name=MySQL-python state=present

  - mysql_db:
      name: "{{ item.name }}"
      state: dump
      target: /tmp/{{ item.name }}.sql
      login_user: root
      login_password: "7h!s!sApw"
    with_items:
      - { name: 'keystone' }
      - { name: 'sahara' }
 #     - { name: 'cinder' }
      - { name: 'heat' }
      - { name: 'glance' }
      - { name: 'neutron' }
      - { name: 'nova' }

  - fetch: src=/tmp/{{ item.name }}.sql dest=/tmp/{{ item.name }}.sql flat=yes
    with_items:
      - { name: 'keystone' }
      - { name: 'sahara' }
 #     - { name: 'cinder' }
      - { name: 'heat' }
      - { name: 'glance' }
      - { name: 'neutron' }
      - { name: 'nova' }

- hosts: control[1]
  sudo: yes
  tasks:

  - mysql_db:
      name: "{{ item.name }}"
      state: absent
      login_user: root
      login_password: "7h!s!sApw"
    with_items:
      - { name: 'keystone' }
      - { name: 'sahara' }
 #     - { name: 'cinder' }
      - { name: 'heat' }
      - { name: 'glance' }
      - { name: 'neutron' }
      - { name: 'nova' }

  - mysql_db:
      name: "{{ item.name }}"
      state: present
      login_user: root
      login_password: "7h!s!sApw"
    with_items:
      - { name: 'keystone' }
      - { name: 'sahara' }
 #     - { name: 'cinder' }
      - { name: 'heat' }
      - { name: 'glance' }
      - { name: 'neutron' }
      - { name: 'nova' }

  - copy: src=/tmp/{{ item.name }}.sql dest=/tmp/{{ item.name }}.sql
    with_items:
      - { name: 'keystone' }
      - { name: 'sahara' }
 #     - { name: 'cinder' }
      - { name: 'heat' }
      - { name: 'glance' }
      - { name: 'neutron' }
      - { name: 'nova' }


  - mysql_db:
      name: "{{ item.name }}"
      state: import
      target: /tmp/{{ item.name }}.sql
      login_user: root
      login_password: "7h!s!sApw"
    with_items:
      - { name: 'keystone' }
      - { name: 'sahara' }
 #     - { name: 'cinder' }
      - { name: 'heat' }
      - { name: 'glance' }
      - { name: 'neutron' }
      - { name: 'nova' }

