---
- hosts: all
  sudo: yes
  vars:
    node1_key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCt5zuXfQS1NhjI2GRRe8V52Zjg26Nn1rGiDxXd1rvJENcrp8/CEvxYKMKMmsuDt3Lt6HdX5isrSofIaGceyT/jAxgGjC4crW/9oB9AtU9rCsLoEc2LL0Z+BICrpidyNLf+3lzFbRK+UAaiZWYGKUzStl30KgfMheOhBGeQHvn4b6LEt22wJEcZ13iVAocvEbnJ2/5m9SfD+uXdQ+1x9Pna/VKwQYKx2S9KqK3nr4Gj48uy+Krm4BbD5YXO2uvcqg7+s7PNPwjYZjrrDgjwof3cxj3mM1qBdBg5F3XCl+4KEOU4eRG3R3XKyHMI3Ee4KiQCHy8xzbNDjgOSVF3tcbIH root@ucs-control01'
    node2_key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDTVEa5DDPygj37pQlmoAFiaqKDEjbnINJG3vYjandabFwNbSJIQcJS+dN31EKzYrs/XB58n9NsIhuOnl3/Dv3azSQZ0XahgHCyevV3Kmsido8dTKSFfB9KSzy2d1r3x6vo87oL6TaCV9hxxjVDhBcoIz2jFPhF2sJ3ISYpgOIrPKw7GJtMibxQAMwZ0uhbMT5uVn1KwFvQfumDQ0o2Av88Al5LefNfAi1A5DhQKqnwJ2CrgTfmYClwES6xN8J1HOGNRy5YKs2b7t4+YK9eZXYDhHv5kXe7rdw7wwTiMHq+XTJVkbTk5gwsuZ/mld9fv5uE3YqL06AInjrtYrlUzePB root@ucs-control02'

  tasks:

  - name: authorize node1 root
    authorized_key: user="root" key="{{ node1_key }}"

  - name: authorize node2 root
    authorized_key: user="root" key="{{ node2_key }}"

- hosts: control
  sudo: yes
  vars:
    password: '7h!s!sApw'
    proxy_ip: 13.7.188.11

  tasks:
  - name: upgrade all packages
    yum: name="*" state=latest

  - name: install dev packages
    yum: name="@Development tools" state=present

  - name: install wget
    yum: name=wget state=present

  - name: install firewalld
    yum: name=firewalld state=present

  - name: enable firewall service
    service: name=firewalld enabled=yes state=started

  - name: ensure epel repository is installed
    yum: name=epel-release state=present

  - name: RDO latest release
    yum: name=https://rdo.fedorapeople.org/rdo-release.rpm state=present

  - name: install packstack tools
    yum: name=openstack-packstack state=present

  - name: update packstack answer file
    template: src=./roles/templates/packstack.j2 dest=/root/packstack.txt

  - name: run packstack
    shell: packstack --answer-file=/root/packstack.txt >& /tmp/pack.out
    
